First tests for retro
LaneHealth/java-ui-checks pull request #3
Opened 2021-03-16 10:14 UTC by SivanovaPro

2021-03-16 11:44 UTC, mikementor requested changes

2021-03-16 11:44 UTC, mikementor commented on pom.xml
> +            <groupId>org.springframework</groupId>
what is it for?

2021-03-16 11:44 UTC, mikementor commented on docker/lanehealth-retro-local.yaml
> +version: '3'
add line in readme for that part

2021-03-18 09:57 UTC, SivanovaPro commented on pom.xml
> +            <groupId>org.springframework</groupId>
I deleted it. Traces of the past

2021-03-18 10:09 UTC, SivanovaPro commented on docker/lanehealth-retro-local.yaml
> +version: '3'
I added an explanation in readme

2021-03-19 06:22 UTC, mikementor approved these changes

2021-03-19 06:23 UTC, merged